name: Pierre Krafft
description: Blogging about programming
meta_description: "Pierre Krafft blog. Blogging about programming"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://zalastax.github.io'
google_analytics: 'UA-62294462-1'

# Details for the RSS feed generator
url:            'http://zalastax.github.io'
author:         'Pierre Krafft'
